FROM ipol:v1-py3.9
COPY src/requirements.txt /requirements.txt
RUN pip install --no-cache-dir -r /requirements.txt && rm /requirements.txt
WORKDIR /workdir/src
COPY . .
RUN mkdir /workdir/bin
RUN cp -r src /workdir/bin/
RUN mkdir /workdir/exec
ENV bin /workdir/bin
ENV PATH $bin:$PATH
WORKDIR /workdir/exec
RUN groupadd -g 1000 ipol
RUN useradd -m -u 1000 -g 1000 ipol
